version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: product
        identifier: raw_gz_product
      - name: sales
        identifier: raw_gz_sales
      - name: ship
        identifier: raw_gz_ship
      - name: adwords
        identifier: raw_gz_adwords
      - name: bing
        identifier: raw_gz_bing
      - name: criteo
        identifier: raw_gz_criteo
      - name: facebook
        identifier: raw_gz_facebook
